Fantom/Fantom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('posts.urls')),
                  path('users/', include('users.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Fantom/posts/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('detail/<int:pk>/<slug:slug>', PostDetail.as_view(), name='detail'),
    path('search/', SearchView.as_view(), name='search'),
    path('post-update/<int:pk>/<slug:slug>', PostUpdateView.as_view(), name='post_update'),
    path('post-delete/<int:pk>/<slug:slug>', DeletePostView.as_view(), name="post_delete"),
    path('category/<int:pk>/<slug:slug>', CategoryDetail.as_view(), name='category-detail'),
    path('tag/<slug:slug>', TagDetail.as_view(), name='tag_detail'),
    path('create-post', PostCreationView.as_view(), name='create-post'),
]

Fantom/users/urls.py
from django.urls import path

from users.views import RegisterView, UserLoginView, UserLogoutView, PasswordChangeView, PasswordChangeDoneView, \
    UserProfileView, UserPostsProfile, UserPostsDetail, AllUsersView
from django.contrib.auth import views as AuthView

app_name = 'users'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('myprofile/', UserPostsProfile.as_view(), name='myprofile'),
    path('user-posts/<int:pk>/', UserPostsDetail.as_view(), name='user-posts'),
    path('profile/<slug:slug>', UserProfileView.as_view(), name='profile'),
    path('all-users/', AllUsersView.as_view(), name='all-users'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password-change/', PasswordChangeView.as_view(), name='change_password'),
    path('password-change-done/', PasswordChangeDoneView.as_view(), name='change_password_done'),
]

Fantom/posts/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.template.defaultfilters import slugify


class Category(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(default='slug', editable=False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def post_count(self):
        return self.posts.all().count()


class Tag(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField(editable=False)

    def __str__(self):
        return self.title

    def save(self, **kwargs):
        self.slug = slugify(self.title)
        super(Tag, self).save(**kwargs)


class Post(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField()
    publishing_date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=True, null=True, upload_to='uploads/')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug = models.SlugField(default='slug', editable=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1, related_name='posts')
    tag = models.ManyToManyField(Tag, related_name='posts', blank=True)
    slider_post = models.BooleanField(default=False)
    hit = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def post_tag(self):
        return ','.join(tag.title for tag in self.tag.all())

    def comment_count(self):
        return self.comments.all().count()


class Comments(models.Model):
    posts = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=100)
    email = models.EmailField()
    content = models.TextField(default='new')
    publishing_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.posts.title

Fantom/posts/forms.py
from captcha.fields import ReCaptchaField
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Field, Submit

from .models import *
from django import forms


class PostCreationForm(forms.ModelForm):
    class Meta:
        model = Post
        widgets = {
            'title': forms.TextInput(attrs={'class': 'single-input', 'placeholder': 'Enter Your Title'}),
            'content': forms.Textarea(attrs={'class': 'single-input', 'placeholder': 'Enter Your content'})
        }
        fields = [
            'title',
            'content',
            'image',
            'category',

        ]


class PostUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(PostUpdateForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'post'
        self.helper.field_class = 'mt-10'
        self.helper.layout = Layout(
            Field('title', css_class='single-input', placeholder='Title'),
            Field('content', css_class='single-input', placeholder='Content'),
            Field('image', css_class='single-input', ),
            Field('category', css_class='single-input', placeholder='Category'),
            Field('tag', css_class='single-input', placeholder='Tag', value=self.instance.post_tag()),
        )
        self.helper.add_input(Submit('submit', 'Update Post', css_class='genric-btn success-border circle'))

    tag = forms.CharField()

    class Meta:
        model = Post
        fields = [
            'title',
            'content',
            'image',
            'category',

        ]


class CreateCommentForm(forms.ModelForm):
    captcha = ReCaptchaField()
    def __init__(self, *args, **kwargs):
        super(CreateCommentForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.layout = Layout(
            Field('name', css_class='form-control', placeholder='Name'),
            Field('email', css_class='form-control', placeholder='Email'),
            Field('content', css_class='form-control mb-10', placeholder='Content'),
            Field('captcha'),
        )
        self.helper.add_input(Submit('submit', 'Comment', css_class='primary-btn submit-btn success-border circle'))

    class Meta:
        model = Comments
        fields = [
            'name',
            'email',
            'content',
        ]

Fantom/posts/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import F, Q
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.edit import FormMixin

from .models import Post, Category, Tag
from .forms import *


class IndexView(ListView):
    template_name = 'posts/index.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 3

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['slider_posts'] = Post.objects.all().filter(slider_post=True)
        return context


class PostDetail(DetailView, FormMixin):
    template_name = 'posts/detail.html'
    model = Post
    context_object_name = 'single'
    form_class = CreateCommentForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        # self.hit = Post.objects.filter(id=self.kwargs['pk']).update(hit=F('hit')+1)
        self.hit = Post.objects.filter(id=self.kwargs['pk']).update(hit=self.object.hit + 1)
        return super(PostDetail, self).get(request, *args, **kwargs)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['previous'] = Post.objects.filter(id__lt=self.kwargs['pk']).order_by('-pk').first()
        context['next'] = Post.objects.filter(id__gt=self.kwargs['pk']).order_by('pk').first()
        context['form'] = self.get_form()
        return context

    def form_valid(self, form):
        self.object = self.get_object()
        if form.is_valid():
            form.instance.posts = self.object
            form.save()
            return super(PostDetail, self).form_valid(form)
        else:
            return super(PostDetail, self).form_invalid(form)

    def post(self, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_valid(form)

    def get_success_url(self):
        return reverse('detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})


class CategoryDetail(ListView):
    model = Post
    template_name = 'categories/category_detail.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])
        return Post.objects.filter(category=self.category).order_by('-id')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryDetail, self).get_context_data(**kwargs)
        context['category'] = Category.objects.get(pk=self.kwargs['pk'])
        return context


class TagDetail(ListView):
    model = Tag
    template_name = 'tags/tag_detail.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        tag = get_object_or_404(Tag, slug=self.kwargs['slug'])
        return Post.objects.filter(tag=tag).order_by('id')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TagDetail, self).get_context_data(**kwargs)
        context['tag'] = Tag.objects.get(slug=self.kwargs['slug'])

        return context


@method_decorator(login_required(login_url='users/login'), name='dispatch')
class PostCreationView(CreateView):
    model = Post
    form_class = PostCreationForm
    template_name = 'posts/create-post.html'

    def get_success_url(self):
        return reverse('detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})

    def form_valid(self, form):
        ## in the creation sefl.kwargs is empty so you must use self.object.fieldname
        form.instance.user = self.request.user
        form.save()

        tags = self.request.POST.get('tag').split(",")
        for tag in tags:
            current_tag = Tag.objects.filter(slug=slugify(tag))
            if current_tag.count() < 1:
                create_tag = Tag.objects.create(title=tag)
                form.instance.tag.add(create_tag)
            else:
                existed_tag = Tag.objects.get(slug=slugify(tag))
                form.instance.tag.add(existed_tag)
        return super(PostCreationView, self).form_valid(form)


@method_decorator(login_required(login_url='users/login'), name='dispatch')
class PostUpdateView(UpdateView):
    model = Post
    form_class = PostUpdateForm
    template_name = 'posts/update-post.html'

    def get_success_url(self):
        return reverse('detail', kwargs={'pk': self.object.pk, 'slug': self.object.slug})

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.tag.clear()

        tags = self.request.POST.get('tag').split(",")
        for tag in tags:
            current_tag = Tag.objects.filter(slug=slugify(tag))
            if current_tag.count() < 1:
                create_tag = Tag.objects.create(tag)
                form.instance.tag.add(create_tag)
            else:
                existed_tag = Tag.objects.get(slug=slugify(tag))
                form.instance.tag.add(existed_tag)
        form.save()
        return super(PostUpdateView, self).form_valid(form)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != self.request.user:
            return HttpResponseRedirect('/')
        return super(PostUpdateView, self).get(request, *args, **kwargs)


class DeletePostView(DeleteView):
    model = Post
    success_url = '/'
    template_name = 'posts/delete.html'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user == request.user:
            self.object.delete()
            return HttpResponseRedirect(self.success_url)
        else:
            return HttpResponseRedirect(self.success_url)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.user != request.user:
            return HttpResponseRedirect(self.success_url)
        return super(DeletePostView, self).get(request, *args, **kwargs)


class SearchView(ListView):
    model = Post
    template_name = 'posts/search.html'
    context_object_name = 'posts'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Post.objects.filter(Q(title__icontains=query) |
                                       Q(content__icontains=query) |
                                       Q(tag__title__icontains=query)
                                       ).order_by('id').distinct()
        return Post.objects.all().order_by('id')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        query = self.request.GET.get('q')
        context['query'] = query

        return context

Fantom/templates/posts/create-post.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
             data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Create Posts</h2>
                <div class="page_link">
                    <a href="{% url 'index' %}">Home</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">

                <h2 style="text-align:center;color:blue">Create Posts</h2>
                <div class="blog_left_sidebar">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.errors %}
                        <div id="error">
                            <div class="inner">
                                <p style="color:red">Please correct the errors below </p>
                                <ul>
                                    {% for field in form %}
                                    {% if field.errors%}
                                    <li> {{ form.label }} : {{field.errors|striptags}}</li>
                                    {%endif%}
                                    {%endfor%}
                                </ul>
                            </div>
                        </div>
                        {%endif%}
                        {% for field in form%}
                        <div class="mt-10">
                            {{ field }}
                        </div>
                        {% endfor %}
                        <input type="text"
                               name="tag"
                               placeholder="Tags must Split by comma"
                               onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Tags'"
                               required=""
                               class="single-input">

                        <input type="submit" class="genric-btn success-border circle"
                               style="float:right;margin-top:30px" value="Add Posts">
                    </form>


                </div>
            </div>
            {% include 'right-side.html' %}
        </div>
    </div>
</section>
<!--================Blog Area =================-->
{% endblock %}

Fantom/templates/posts/delete.html
{% extends 'base.html' %}
{% load static %}

{% block content%}

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
             data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Delete Posts</h2>
                <div class="page_link">
                    <a href="{% url 'index' %}">Home</a>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="blog_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">

                <h2 style="text-align:center;color:blue">Are you sure to delete this Post?.</h2>
                <div class="blog_left_sidebar">
                    <form method="post">
                        {% csrf_token %}
                        <a href="{% url 'detail' object.pk object.slug %}" class="genric-btn info circle">NO</a>
                        <button type="submit" class="genric-btn danger circle">Yes</button>
<!--                        <a href="{% url 'detail' object.pk object.slug %}" >Submit</a>-->

                    </form>
                </div>
            </div>
            {% include 'right-side.html' %}
        </div>
    </div>
</section>
<!--================Blog Area =================-->
{% endblock %}

Fantom/templates/posts/detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
             data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Blog Post Details</h2>
                <div class="page_link">
                    <a href="{% url 'index' %}">Home</a>
                    <a href="#">Post Details</a>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->

<!--================Blog Area =================-->
<section class="blog_area p_120 single-post-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="main_blog_details">
                    <img class="img-fluid" src="{{ single.image.url }}" alt="">
                    <a href="#"><h4>{{single.title}}</h4></a>
                    <div class="user_details">
                        <div class="float-left">
                            {% for tag in single.tag.all %}
                            <a class="cat" href="{% url 'tag_detail' slug=tag.slug %}">{{ tag.title }}</a>
                            {% endfor %}
                        </div>
                        <div class="float-right">
                            <div class="media">
                                <div class="media-body">
                                    <h5><a href="{% url 'users:user-posts' pk=single.user.pk %}">{{ single.user.username }}</a></h5>
                                    <p>{{ single.publishing_date }}</p>
                                </div>
                                <div class="d-flex">
                                    <img width='60px' height="60px" src="{% static 'img/blog/khaled.jpeg' %}" alt="">
                                </div>
                            </div>
                        </div>
                    </div>
                    <p>{{single.content}}</p>
                    {% if single.user == request.user %}
                    <a href="{% url 'post_update' single.pk single.slug %}" class="genric-btn info circle">Update</a>
                    <a href="{% url 'post_delete' single.pk single.slug %}" class="genric-btn danger circle">Delete</a>
                    {% endif %}
                    <div class="news_d_footer">
                        <a href="#"><i class="lnr lnr lnr-heart"></i>Lily and 4 people like this</a>
                        <a class="justify-content-center ml-auto" href="#"><i class="lnr lnr lnr-bubble"></i>06 Comments</a>
                        <div class="news_socail ml-auto">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-youtube-play"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                            <a href="#"><i class="fa fa-rss"></i></a>
                        </div>
                    </div>
                </div>
                <div class="navigation-area">
                    <div class="row">
                        {% if previous %}
                        <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                            <div class="thumb">
                                <a href="{% url 'detail' pk=previous.pk slug=previous.slug %}"><img class="img-fluid"
                                                                                                    width="60px%"
                                                                                                    height="60px"
                                                                                                    src="{{ previous.image.url }}"
                                                                                                    alt=""></a>
                            </div>
                            <div class="arrow">
                                <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                            </div>
                            <div class="detials">
                                <p>Prev Post</p>
                                <a href="{% url 'detail' pk=previous.pk slug=previous.slug %}"><h4>{{
                                    previous.title}}</h4></a>
                            </div>
                        </div>
                        {% else %}
                        <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                            <div class="thumb">
                                <a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}" alt=""></a>
                            </div>
                            <div class="arrow">
                                <a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
                            </div>
                            <div class="detials">
                                <p>No Prev Post</p>
                                <a href="#"><h4>No Prev Post</h4></a>
                            </div>
                        </div>

                        {% endif %}
                        {% if next %}
                        <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                            <div class="detials">
                                <p>Next Post</p>
                                <a href="{% url 'detail' pk=next.pk slug=next.slug %}"><h4>{{ next.title}}</h4>
                                </a>

                            </div>
                            <div class="arrow">
                                <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                            </div>
                            <div class="thumb">
                                <a href="{% url 'detail' pk=next.pk slug=next.slug %}"><img class="img-fluid"
                                                                                            width="60px" height="60px"
                                                                                            src="{{ next.image.url }}"
                                                                                            alt=""></a>
                            </div>
                        </div>
                        {% else %}
                        <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                            <div class="detials">
                                <p>No Next Post</p>
                                <a href="#"><h4>No Next Post</h4></a>
                            </div>
                            <div class="arrow">
                                <a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
                            </div>
                            <div class="thumb">
                                <a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}" alt=""></a>
                            </div>
                        </div>

                        {% endif %}
                    </div>
                </div>
                <div class="comments-area">
                    <h4>{{ single.comment_count }} Comments</h4>
                    {% for comment in single.comments.all %}
                    <div class="comment-list">
                        <div class="single-comment justify-content-between d-flex">
                            <div class="user justify-content-between d-flex">
                                <div class="thumb">
                                    <img src="{% static 'img/blog/c1.jpg'%}" alt="">
                                </div>
                                <div class="desc">
                                    <h5><a href="#">{{ comment.name }}</a></h5>
                                    <p href="#">{{ comment.email }}</p>
                                    <p class="date">{{ comment.publishing_date }}</p>
                                    <p class="comment">
                                        {{ comment.content }}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="comment-form">
                    <h4>Leave a Reply</h4>
                    {% if form.errors %}
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        <div id="form-errors">
                            {% for key,value in form.errors.items %}
                            <span class="fieldWrapper">
                                <strong>{{ key }} :</strong> {{ value }}
                            </span>
                            {% endfor %}
                        </div>
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                          </button>

                    </div>
                    {% endif %}
                    {% crispy form %}
                </div>
            </div>
            {% include 'right-side.html' %}

        </div>
    </div>
</section>
<!--================Blog Area =================-->
{% endblock %}

Fantom/templates/posts/update-post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}

<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="banner_inner d-flex align-items-center">
        <div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0"
             data-background=""></div>
        <div class="container">
            <div class="banner_content text-center">
                <h2>Update Posts</h2>
                <div class="page_link">
                    <a href="{% url 'index' %}">Home</a>
                </div>
            </div>
        </div>
    </div>
</section>


<section class="blog_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">

                <h2 style="text-align:center;color:blue">Update Posts</h2>
                <div class="blog_left_sidebar">
                    {% crispy form %}
                </div>
            </div>
            {% include 'right-side.html' %}
        </div>
    </div>
</section>
<!--================Blog Area =================-->
{% endblock %}